version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: poc-sig-mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd!
      MSSQL_PID: Developer
    ports:
      - "1434:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - poc-sig-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Passw0rd! -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mssql_data:
    driver: local

networks:
  poc-sig-network:
    driver: bridge